in the JUnit tests... (1206)

load from the ZRH repository the following 2 plugins.
org.eclipse.jdt.ui.tests
org.junit

Excecute main of JavaModelUtilTest. (assumes all plugins at default location), 
or use the junit ui launcher.
The first test fails while deleting a project, all following because an 
internal JAR still exists.
It seems there is stream a InputStream on the JAR which is not closed. I've 
seen this problem also while working in Eclipse.

1) testFindType(org.eclipse.jdt.ui.tests.core.JavaModelUtilTest)
org.eclipse.core.internal.resources.ResourceException: Problems encountered 
while deleting resources.

Stack trace:
   java/lang/Throwable.<init>()V
   java/lang/Throwable.<init>(Ljava/lang/String;)V
   org/eclipse/core/runtime/CoreException.<init>
(Lorg/eclipse/core/runtime/IStatus;)V
   org/eclipse/core/internal/resources/ResourceException.<init>
(Lorg/eclipse/core/runtime/IStatus;)V
   org/eclipse/core/internal/resources/Project.delete
(ZZLorg/eclipse/core/runtime/IProgressMonitor;)V
   org/eclipse/jdt/testplugin/JavaProjectHelper.delete
(Lorg/eclipse/jdt/core/IJavaProject;)V
   org/eclipse/jdt/ui/tests/core/JavaModelUtilTest.tearDown()V
   junit/framework/TestCase.runBare()V
   junit/framework/TestResult$1.protect()V
   junit/framework/TestResult.runProtected
(Ljunit/framework/Test;Ljunit/framework/Protectable;)V
   junit/framework/TestResult.run(Ljunit/framework/TestCase;)V
   junit/framework/TestCase.run(Ljunit/framework/TestResult;)V
   junit/framework/TestSuite.runTest
(Ljunit/framework/Test;Ljunit/framework/TestResult;)V
   junit/framework/TestSuite.run(Ljunit/framework/TestResult;)V
   junit/textui/TestRunner.doRun(Ljunit/framework/Test;Z)
Ljunit/framework/TestResult;
   junit/textui/TestRunner.run(Ljunit/framework/Test;)V
   org/eclipse/jdt/testplugin/TestWorkbench.runEventLoop()V
   org/eclipse/ui/internal/Workbench.run(Ljava/lang/Object;)Ljava/lang/Object;
   org/eclipse/core/internal/boot/InternalBootLoader.run
(Ljava/lang/String;Ljava/net/URL;Ljava/lang/String;[Ljava/lang/String;)
Ljava/lang/Object;
   org/eclipse/core/boot/BootLoader.run
(Ljava/lang/String;Ljava/net/URL;Ljava/lang/String;[Ljava/lang/String;)
Ljava/lang/Object;
   java/lang/reflect/Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)
Ljava/lang/Object;
   org/eclipse/core/launcher/Main.basicRun([Ljava/lang/String;)
Ljava/lang/Object;
   org/eclipse/core/launcher/Main.run([Ljava/lang/String;)Ljava/lang/Object;
   org/eclipse/jdt/testplugin/TestPluginLauncher.run
(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Class;[Ljava/lang/String;)V
   org/eclipse/jdt/testplugin/TestPluginLauncher.run
(Ljava/lang/String;Ljava/lang/Class;[Ljava/lang/String;)V
   org/eclipse/jdt/ui/tests/core/JavaModelUtilTest.main([Ljava/lang/String;)V

2) testFindType2(org.eclipse.jdt.ui.tests.core.JavaModelUtilTest)
org.eclipse.core.internal.resources.ResourceException: 
Resource /TestProject1/mylib.jar already exists.

Stack trace:
   java/lang/Throwable.<init>()V
   java/lang/Throwable.<init>(Ljava/lang/String;)V
   org/eclipse/core/runtime/CoreException.<init>
(Lorg/eclipse/core/runtime/IStatus;)V
   org/eclipse/core/internal/resources/ResourceException.<init>
(ILorg/eclipse/core/runtime/IPath;Ljava/lang/String;Ljava/lang/Throwable;)V
   org/eclipse/core/internal/resources/Resource.checkDoesNotExist(IZ)V
   org/eclipse/core/internal/resources/Resource.checkDoesNotExist()V
   org/eclipse/core/internal/resources/File.create
(Ljava/io/InputStream;ZLorg/eclipse/core/runtime/IProgressMonitor;)V
...

in the JUnit tests... (1206)

load from the ZRH repository the following 2 plugins.
org.eclipse.jdt.ui.tests
org.junit

Excecute main of JavaModelUtilTest. (assumes all plugins at default location), 
or use the junit ui launcher.
The first test fails while deleting a project, all following because an 
internal JAR still exists.
It seems there is stream a InputStream on the JAR which is not closed. I've 
seen this problem also while working in Eclipse.

1) testFindType(org.eclipse.jdt.ui.tests.core.JavaModelUtilTest)
org.eclipse.core.internal.resources.ResourceException: Problems encountered 
while deleting resources.

Stack trace:
   java/lang/Throwable.<init>()V
   java/lang/Throwable.<init>(Ljava/lang/String;)V
   org/eclipse/core/runtime/CoreException.<init>
(Lorg/eclipse/core/runtime/IStatus;)V
   org/eclipse/core/internal/resources/ResourceException.<init>
(Lorg/eclipse/core/runtime/IStatus;)V
   org/eclipse/core/internal/resources/Project.delete
(ZZLorg/eclipse/core/runtime/IProgressMonitor;)V
   org/eclipse/jdt/testplugin/JavaProjectHelper.delete
(Lorg/eclipse/jdt/core/IJavaProject;)V
   org/eclipse/jdt/ui/tests/core/JavaModelUtilTest.tearDown()V
   junit/framework/TestCase.runBare()V
   junit/framework/TestResult$1.protect()V
   junit/framework/TestResult.runProtected
(Ljunit/framework/Test;Ljunit/framework/Protectable;)V
   junit/framework/TestResult.run(Ljunit/framework/TestCase;)V
   junit/framework/TestCase.run(Ljunit/framework/TestResult;)V
   junit/framework/TestSuite.runTest
(Ljunit/framework/Test;Ljunit/framework/TestResult;)V
   junit/framework/TestSuite.run(Ljunit/framework/TestResult;)V
   junit/textui/TestRunner.doRun(Ljunit/framework/Test;Z)
Ljunit/framework/TestResult;
   junit/textui/TestRunner.run(Ljunit/framework/Test;)V
   org/eclipse/jdt/testplugin/TestWorkbench.runEventLoop()V
   org/eclipse/ui/internal/Workbench.run(Ljava/lang/Object;)Ljava/lang/Object;
   org/eclipse/core/internal/boot/InternalBootLoader.run
(Ljava/lang/String;Ljava/net/URL;Ljava/lang/String;[Ljava/lang/String;)
Ljava/lang/Object;
   org/eclipse/core/boot/BootLoader.run
(Ljava/lang/String;Ljava/net/URL;Ljava/lang/String;[Ljava/lang/String;)
Ljava/lang/Object;
   java/lang/reflect/Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)
Ljava/lang/Object;
   org/eclipse/core/launcher/Main.basicRun([Ljava/lang/String;)
Ljava/lang/Object;
   org/eclipse/core/launcher/Main.run([Ljava/lang/String;)Ljava/lang/Object;
   org/eclipse/jdt/testplugin/TestPluginLauncher.run
(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Class;[Ljava/lang/String;)V
   org/eclipse/jdt/testplugin/TestPluginLauncher.run
(Ljava/lang/String;Ljava/lang/Class;[Ljava/lang/String;)V
   org/eclipse/jdt/ui/tests/core/JavaModelUtilTest.main([Ljava/lang/String;)V

2) testFindType2(org.eclipse.jdt.ui.tests.core.JavaModelUtilTest)
org.eclipse.core.internal.resources.ResourceException: 
Resource /TestProject1/mylib.jar already exists.

Stack trace:
   java/lang/Throwable.<init>()V
   java/lang/Throwable.<init>(Ljava/lang/String;)V
   org/eclipse/core/runtime/CoreException.<init>
(Lorg/eclipse/core/runtime/IStatus;)V
   org/eclipse/core/internal/resources/ResourceException.<init>
(ILorg/eclipse/core/runtime/IPath;Ljava/lang/String;Ljava/lang/Throwable;)V
   org/eclipse/core/internal/resources/Resource.checkDoesNotExist(IZ)V
   org/eclipse/core/internal/resources/Resource.checkDoesNotExist()V
   org/eclipse/core/internal/resources/File.create
(Ljava/io/InputStream;ZLorg/eclipse/core/runtime/IProgressMonitor;)V
...
Is the new builder name environment properly closing the opened JAR/ZIP files ? 
Look at the batch environment for an example (added #reset API).
Now close the zip file when the build is finished.
Hello world !!!!!!!!!!
Hello world.
Hello world.
Hello world.


Problems with deleting project



Bug 336740 - JUnit 4.8.2 

Bug 416740: Avoid using nested jars 

Bug 416740: Avoid using nested jars 

Bug 416740: Avoid using nested jars 

Bug 416740: Avoid using nested jars 

HEAD - Fix for 276740, 276741 

bug 186740: discard cached CategorizedProblems when build is complete. 