Build: 20020328

Description:
I'm running some benchmarks in Eclipse using the JUnit Test Plugins launcher 
and I occasionally run into situations where my benchmark causes an exception, 
and JUnit fails to display the stack trace.  I think it's because 
FailureTraceView.fillTable(String trace) assumes that there is

Build: 20020328

Description:
I'm running some benchmarks in Eclipse using the JUnit Test Plugins launcher 
and I occasionally run into situations where my benchmark causes an exception, 
and JUnit fails to display the stack trace.  I think it's because 
FailureTraceView.fillTable(String trace) assumes that there is
I accidentally hit commit....

I think FailureTraceView.fillTable(String trace) assumes that trace contains 
a '\n', but I'm causing exceptions whose stack traces don't contain a '\n'.  
This is rather frustrating because I have no way of knowing what exception 
happened in my test because the StringIndexOutOfBoundsException gets in the 
way....
the code is not writtern properly needs to be rewritten...
made the code more sensitive with regard to newlines.
pls try again and reopen bug if you can reproduce the problem.


StringIndexOutOfBoundsException in JUnit's FailureTraceView



126317 [quick fix] for typos within @SuppressWarnings values 

126317 [quick fix] for typos within @SuppressWarnings values 