Test Case:

public class TT {
	public void foo() {
		new TT();
	}
	public void bar() {
		new TT();
	}
}


- select new TT in bar
- introduce factory

observer: you get an internal error.

Caused by: java.lang.NullPointerException
	at java.lang.Throwable.<init>(Throwable.java)
	at java.lang.Throwable.<init>(Throwable.java)
	at java.lang.NullPointerException.<init>(NullPointerException.java:60)
	at 
org.eclipse.jdt.internal.core.search.matching.SearchPattern.createPattern
(SearchPattern.java:630)
	at org.eclipse.jdt.core.search.SearchEngine.createSearchPattern
(SearchEngine.java:317)
	at 
com.ibm.watson.refactoring.IntroduceFactoryRefactoring.createSearchPattern
(IntroduceFactoryRefactoring.java:396)
	at 
com.ibm.watson.refactoring.IntroduceFactoryRefactoring.searchForCallsTo
(IntroduceFactoryRefactoring.java:430)
	at 
com.ibm.watson.refactoring.IntroduceFactoryRefactoring.findAllCallsTo
(IntroduceFactoryRefactoring.java:450)
	at com.ibm.watson.refactoring.IntroduceFactoryRefactoring.checkInput
(IntroduceFactoryRefactoring.java:501)
	at org.eclipse.jdt.internal.ui.refactoring.CheckConditionsOperation.run
(CheckConditionsOperation.java:65)
	at org.eclipse.jdt.internal.ui.refactoring.CreateChangeOperation.run
(CreateChangeOperation.java:100)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run
(ModalContext.java:101)

Test Case:

public class TT {
	public void foo() {
		new TT();
	}
	public void bar() {
		new TT();
	}
}


- select new TT in bar
- introduce factory

observer: you get an internal error.

Caused by: java.lang.NullPointerException
	at java.lang.Throwable.<init>(Throwable.java)
	at java.lang.Throwable.<init>(Throwable.java)
	at java.lang.NullPointerException.<init>(NullPointerException.java:60)
	at 
org.eclipse.jdt.internal.core.search.matching.SearchPattern.createPattern
(SearchPattern.java:630)
	at org.eclipse.jdt.core.search.SearchEngine.createSearchPattern
(SearchEngine.java:317)
	at 
com.ibm.watson.refactoring.IntroduceFactoryRefactoring.createSearchPattern
(IntroduceFactoryRefactoring.java:396)
	at 
com.ibm.watson.refactoring.IntroduceFactoryRefactoring.searchForCallsTo
(IntroduceFactoryRefactoring.java:430)
	at 
com.ibm.watson.refactoring.IntroduceFactoryRefactoring.findAllCallsTo
(IntroduceFactoryRefactoring.java:450)
	at com.ibm.watson.refactoring.IntroduceFactoryRefactoring.checkInput
(IntroduceFactoryRefactoring.java:501)
	at org.eclipse.jdt.internal.ui.refactoring.CheckConditionsOperation.run
(CheckConditionsOperation.java:65)
	at org.eclipse.jdt.internal.ui.refactoring.CreateChangeOperation.run
(CreateChangeOperation.java:100)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run
(ModalContext.java:101)
Isn't actually related to two constructor calls; issue is that the constructor 
being called is implicitly defined. Fixed in latest build.


Internal error when two constructors exist in same CU

