CatchClause begins on the 'e' temp here:

package p;
class A{
	void m(){
		try{
		} catch (Exception e){
			m();			
		}
	}
}

CatchClause begins on the 'e' temp here:

package p;
class A{
	void m(){
		try{
		} catch (Exception e){
			m();			
		}
	}
}
The problem comes from the fact that the position of the catch keyword in not stored. I will fix it 
with a manual scanning.

Fixed and released in HEAD.
