package p;

import java.io.IOException;

class A{	
	void f() throws IOException{
		/*[*/try{
			f();
		} catch (IOException e){
			throw new IOException();
		}/*]*/
	}
}

btw - i don't think the recursion has anything to do with this (just made the 
example shorter)

package p;

import java.io.IOException;

class A{	
	void f() throws IOException{
		/*[*/try{
			f();
		} catch (IOException e){
			throw new IOException();
		}/*]*/
	}
}

btw - i don't think the recursion has anything to do with this (just made the 
example shorter)
Fixed in build > 20020124
