in the following code

import java.io.IOException;

/**
 * @version 	1.0
 * @author
 */
public class Uuu {
	public Object f() throws IOException {
		return new Object();
	}
	
	public void a() {
		Object b= f();
		b= null;
	}
}

Select the statement Object b= f(); and perform surround with try/catch

you get:
	public void a() {
		Object b= f();
		try {
		} catch(IOException e) {
		}
		b= null;
	}

in the following code

import java.io.IOException;

/**
 * @version 	1.0
 * @author
 */
public class Uuu {
	public Object f() throws IOException {
		return new Object();
	}
	
	public void a() {
		Object b= f();
		b= null;
	}
}

Select the statement Object b= f(); and perform surround with try/catch

you get:
	public void a() {
		Object b= f();
		try {
		} catch(IOException e) {
		}
		b= null;
	}
Fixed in build > I20020425
